FLASK_ENV=development
SUPABASE_URL=https://imhdpixsmgwlrvpqiqel.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltaGRwaXhzbWd3bHJ2cHFpcWVsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY2OTQ5OTAxOSwiZXhwIjoxOTg1MDc1MDE5fQ.uAz7zAsOnv0bp_jVce2U99UokDkbkUdTWU5JFSHs46Y